language: cpp
dist: xenial
os: linux

addons:
  apt:
    packages:
      - zstd
before_install:
  - pip install --user cpp-coveralls
script:
  - mkdir build && cd build && cmake .. -DUSE_GCOV=TRUE
  - cmake --build . -j 6
  - ctest -V
after_success:
  - cd .. && coveralls -E ".*/HavokLib/build/.*.((c)|(h))((pp)|(c)|(xx))?$" -e test -e 3rd_party --gcov-options '\-lp' > /dev/null
