language: cpp
dist: xenial
os: linux

before_install:
  - pip install --user cpp-coveralls
  - sudo .ci/install_pugi.sh ${TRAVIS_CPU_ARCH}

script:
  - mkdir build && cd build && cmake .. -DUSE_GCOV=TRUE
  - cmake --build . -j 6
  - ctest -V

after_success:
  - cd .. && coveralls -E ".*/PreCore/build/.*.c((pp)|(c)|(xx))?$" -e MAXex -e test -e datas/unit_testing.hpp --gcov-options '\-lp'
